name: Kobo Daily Sync

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        run: python main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages

      - name: Notify Instapaper
        env:
          INSTAPAPER_USER: ${{ secrets.INSTAPAPER_USER }}
          INSTAPAPER_PASS: ${{ secrets.INSTAPAPER_PASS }}
        run: |
          # Wait 90s for GitHub to actually push the file to the web
          sleep 90
          curl -u "$INSTAPAPER_USER:$INSTAPAPER_PASS" \
          https://www.instapaper.com/api/add \
          -d "url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.html"