name: Kobo Daily Sync

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        env:
          # This allows main.py to send the 10 Guardian/NYT links
          INSTAPAPER_USER: ${{ secrets.INSTAPAPER_USER }}
          INSTAPAPER_PASS: ${{ secrets.INSTAPAPER_PASS }}
        run: python main.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages

      - name: Notify Instapaper
        env:
          # This allows the final 'ping' so Instapaper fetches the newsletter
          INSTAPAPER_USER: ${{ secrets.INSTAPAPER_USER }}
          INSTAPAPER_PASS: ${{ secrets.INSTAPAPER_PASS }}
        run: |
          sleep 180
          curl -u "$INSTAPAPER_USER:$INSTAPAPER_PASS" \
          https://www.instapaper.com/api/add \
          -d "url=https://lirohdesign.github.io/kobo-newspaper/index.html"